import { Paper } from '../../../model/paper';
import { camelCaseKeys } from '../../../helpers/camelCaseKeys';

export const paperSource = camelCaseKeys({
  destination: 'http://www.nature.com/articles/s41586-018-0337-2',
  doi: '10.1038/s41586-018-0337-2',
  host: 'www.nature.com',
  paper_id: 2884430236,
  source: 'http://www.nature.com/articles/s41586-018-0337-2',
});

export const paperWithNote = camelCaseKeys({
  note: 'sdfdsf',
  paper: {
    id: 2793122029,
    title: 'Audio-visual speech processing system for Polish applicable to human-computer interaction',
    year: 2018,
    lang: null,
    doi: '10.7494/csci.2018.19.1.2398',
    volume: '19',
    issue: '1',
    pageStart: null,
    pageEnd: null,
    referenceCount: 0,
    citedCount: 0,
    fosCount: 0,
    urlCount: 0,
    commentCount: 0,
    journal: {
      id: 57947533,
      title: 'Computer Science',
      issn: '1508-2806',
      webPage: 'http://www.csci.agh.edu.pl/',
      impactFactor: null,
      paperCount: 10430,
      citationCount: 5832,
      sci: false,
      fosList: null,
      title_abbrev: null,
    },
    authors: [
      {
        paperId: 2793122029,
        id: 1123671428,
        name: 'Tomasz Jadczyk',
        organization: 'AGH University of Science and Technology',
        affiliation: {
          id: 686019,
          name: 'AGH University of Science and Technology',
          name_abbrev: null,
        },
        order: 1,
        hindex: 5,
        is_layered: false,
      },
    ],
    fosList: [],
    urls: [],
    figures: [],
    images: [],
    comments: [],
    published_date: '2018-01-01',
    abstract: null,
    author_count: 1,
    best_pdf: null,
    conference_instance: null,
  },
  collection_id: 287,
  paper_id: 2793122029,
});

export const paperWithFigureAndManyAuthors: Paper = camelCaseKeys({
  id: 2625710583,
  title: 'Machine Learning Predicts Laboratory Earthquakes',
  year: 2017,
  published_date: '2017-09-28',
  doi: '10.1002/2017GL074677',
  volume: '44',
  issue: '18',
  author_count: 6,
  reference_count: 38,
  cited_count: 32,
  journal: {
    id: 36624081,
    title: 'Geophysical Research Letters',
    title_abbrev: 'GEOPHYS RES LETT',
    issn: '0094-8276',
    web_page: 'http://onlinelibrary.wiley.com/journal/10.1002/(ISSN)1944-8007',
    impact_factor: 4.578,
    paper_count: 51566,
    citation_count: 1475456,
    sci: true,
  },
  conference_instance: null,
  authors: [
    {
      id: 2334418847,
      name: 'Bertrand Rouet-Leduc',
      affiliation: {
        id: 241749,
        name: 'University of Cambridge',
        name_abbrev: null,
      },
      paper_count: 20,
      citation_count: 113,
      order: 1,
      hindex: 6,
      profile_image_url: null,
      is_layered: false,
    },
    {
      id: 2625150949,
      name: 'Claudia Hulbert',
      affiliation: {
        id: 1343871089,
        name: 'Los Alamos National Laboratory',
        name_abbrev: 'LANL',
      },
      paper_count: 13,
      citation_count: 59,
      order: 2,
      hindex: 4,
      profile_image_url: null,
      is_layered: false,
    },
    {
      id: 2510408987,
      name: 'Nicholas Lubbers',
      affiliation: {
        id: 111088046,
        name: 'Boston University',
        name_abbrev: 'BU',
      },
      paper_count: 17,
      citation_count: 311,
      order: 3,
      hindex: 7,
      profile_image_url: null,
      is_layered: false,
    },
    {
      id: 2109894735,
      name: 'Kipton Barros',
      affiliation: {
        id: 1343871089,
        name: 'Los Alamos National Laboratory',
        name_abbrev: 'LANL',
      },
      paper_count: 71,
      citation_count: 521,
      order: 4,
      hindex: 12,
      profile_image_url: null,
      is_layered: false,
    },
    {
      id: 2136226339,
      name: 'C. J. Humphreys',
      affiliation: {
        id: 241749,
        name: 'University of Cambridge',
        name_abbrev: null,
      },
      paper_count: 713,
      citation_count: 13864,
      order: 5,
      hindex: 50,
      profile_image_url: null,
      is_layered: false,
    },
    {
      id: 2104038104,
      name: 'Paul A. Johnson',
      affiliation: {
        id: 1343871089,
        name: 'Los Alamos National Laboratory',
        name_abbrev: 'LANL',
      },
      paper_count: 245,
      citation_count: 5246,
      order: 6,
      hindex: 35,
      profile_image_url: null,
      is_layered: false,
    },
  ],
  fos_list: [],
  urls: [],
  abstract: null,
  title_highlighted: '<b>Machine</b><b> Learning</b> Predicts Laboratory Earthquakes',
  abstract_highlighted:
    'We apply <b>machine</b><b> learning</b> to data sets from shear laboratory experiments, with the goal of identifying hidden signals that precede earthquakes. Here we show that by listening to the acoustic signal emitted by a laboratory fault, <b>machine</b><b> learning</b> can predict the time remaining before it fails with great accuracy. These predictions are based solely on the instantaneous physical characteristics of the acoustical signal and do not make use of its history. Surprisingly, <b>machine</b><b> learning</b> identifies a signal emitted from the fault zone previously thought to be low-amplitude noise that enables failure forecasting throughout the laboratory quake cycle. We infer that this signal originates from continuous grain motions of the fault gouge as the fault blocks displace. We posit that applying this approach to continuous seismic data may lead to significant advances in identifying currently unknown signals, in providing new insights into fault physics, and in placing bounds on fault failure times.',
  figures: [
    {
      type: 'FIGURE',
      name: 'figure-1',
      caption:
        'Figure 1. Random Forest (RF) approach for predicting time remaining before failure. (a) Shear stress (black curve) exhibits sharp drops, indicating failure events (laboratory earthquakes). We wish to predict the time remaining before the next failure derived from the shear stress drops (red curve), using only the (b) acoustic emission (dynamic strain) data. The dashed rectangle represents a moving time window; each window generates a single point on each feature curve below (e.g., variance and kurtosis). (c) The RF model predicts the time remaining before the next failure by averaging the predictions of 1,000 decision trees for each time window. Each tree makes its prediction (white leaf node), following a series of decisions (colored nodes) based on features of the acoustic signal during the current window (see supporting information S1). (d) The RF prediction (blue line) on data it has never seen (testing data) with 90% confidence intervals (blue shaded region). The predictions agree remarkably well with the actual remaining times before failure (red curve). We emphasize that the testing data are entirely independent of the training data, and were not used to construct the model. Data are from experiment number p2394.',
      path: 'prod/2625710583/figures/figure-1.jpg',
    },
    {
      type: 'FIGURE',
      name: 'figure-2',
      caption:
        'Figure 2. Time remaining before the next failure predicted by the Random Forest. As in Figure 1a, the red lines show the actual time before failure (Y axis) versus experimental run time (X axis). The red dashed line shows the time remaining before the next failure (derived from the shear stress data), and the blue line shows the corresponding prediction of the RF regression model (derived exclusively from the “instantaneous” acoustic data). The blue-shaded region indicates the 5th and 95th percentiles of the forecast; that is, 90% of the trees that comprise the forest made a forecast within these bounds. The inset emphasizes predictions on aperiodic slip behavior. The RF does a remarkable job of forecasting slip times even with aperiodic data. The RF was trained on ≈150 s of data (≈10 slip events), and tested on the following ≈150 s, shown here. We stress that the predictions from each time are entirely independent of past and future history—each blue point is a “now” prediction. The data points can be scrambled in time and the predictions remain the same. Data are from experiment number p2394.',
      path: 'prod/2625710583/figures/figure-2.jpg',
    },
    {
      type: 'FIGURE',
      name: 'figure-3',
      caption:
        'Figure 3. The physics of failure. The RF identifies two classes of signals and uses them to predict failure. (a) Shear stress and dynamic strain encompassing two failure events. (b) Zoom of dynamic strain when failure is in the distant future. This newly identified signal, termed “laboratory tremor” offers precise predictive capability of the next failure time. (c) Zoom of a classic, impulsive acoustic emission observed in the critically stressed region just preceding failure (note that vertical scale is different for two signals). Such signals are routinely identified preceding failure in the shear apparatus, in brittle failure in most materials and in some earthquakes. Data are from experiment number p2394.',
      path: 'prod/2625710583/figures/figure-3.jpg',
    },
  ],
  missing_keywords: [],
  relation: null,
  is_layered: false,
});
