import { CURRENT_ONBOARDING_PROGRESS_STEP } from './types';

export const isStepOptional = (step: CURRENT_ONBOARDING_PROGRESS_STEP) => {
  return (
    step === CURRENT_ONBOARDING_PROGRESS_STEP.MATCH_UNSYNCED_PUBS ||
    step === CURRENT_ONBOARDING_PROGRESS_STEP.SELECT_REPRESENTATIVE_PUBS
  );
};
